config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      namespace :user do
        resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resources :payment_methods
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    collection do
      patch :info
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/views/shared/_account_navbar.html.erb
<div class="bg-white border border-gray-200 rounded text-sm font-medium">
  <%= nav_link_to t(".profile"), edit_user_registration_path, class: "block no-underline p-3 px-6 rounded-t", active_class: "bg-blue-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%= nav_link_to t(".password"), edit_account_password_path, class: "block no-underline p-3 px-6", active_class: "bg-blue-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%= nav_link_to t(".connected_accounts"), user_connected_accounts_path, class: "block no-underline p-3 px-6", active_class: "bg-blue-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" if Devise.omniauth_configs.any? %>
  <% unless turbo_native_app? %>
    <%= nav_link_to t(".billing"), subscriptions_path, class: "block no-underline p-3 px-6", active_class: "bg-blue-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: ["/subscriptions", "/payment_methods"] if Jumpstart.config.payments_enabled? %>
  <% end %>
  <%= nav_link_to t(".accounts"), accounts_path, class: "block no-underline p-3 px-6", active_class: "bg-blue-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: "/accounts" %>
  <%= nav_link_to t(".api_tokens"), api_tokens_path, class: "block no-underline p-3 px-6 rounded-b", active_class: "bg-blue-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: "/api_tokens" %>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-error mb-6" role="alert">
    <div class="flex items-start justify-start">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current icon mr-4 mt-1 flex-no-shrink" role="img" aria-labelledby="f1yx75u7nv0lvn6ck4z10w7lksjmk2f"><title id="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">Icons/close outline</title><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z"></path></svg>

      <div>
        <h4 class="font-black text-sm uppercase tracking">
          <%= I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase) %>
        </h4>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_favicons.html.erb
<meta name="theme-color" content="#ffffff">
<link rel="icon" href="/favicon.ico" sizes="any"><!-- 32×32 -->
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png"><!-- 180×180 -->
<link rel="manifest" href="/site.webmanifest">

<%#
<!-- Twitter
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@YourAccount">
<meta name="twitter:creator" content="@YourAccount">
<meta name="twitter:title" content="Title of your page">
<meta name="twitter:url" content="URL of your page">
<meta name="twitter:description" content="Your description here">
<meta name="twitter:image:src" content="URL of image">
-->

<!-- Open Graph
<meta property="og:title" content="ENTER PAGE TITLE">
<meta property="og:type" content="website">
<meta property="og:url" content="ENTER PAGE URL">
<meta property="og:image" content="URL OF IMAGE">
<meta property="og:image:width" content="1240">
<meta property="og:image:height" content="650">
<meta property="og:site_name" content="ENTER YOUR SITE NAME">
<meta property="og:description" content="ENTER YOUR PAGE DESCRIPTION">
<meta property="fb:app_id" content="ENTER YOUR FB APP ID">
-->
%>

app/views/shared/_flash.html.erb
<% if current_user != true_user %>
  <div class="flex items-center justify-center px-2 py-1 text-sm text-blue-200 bg-blue-600 font-semibold" role="alert">
    <span class="mr-2">Logged in as <b><%= link_to "User ##{current_user.id}", admin_user_path(current_user), class: "text-blue-200 underline hover:text-blue-100" %></b></span>
    <%= button_to admin_user_impersonate_path(current_user), method: :delete, form_class: "inline-block", class: "btn btn-primary btn-small" do %>
      Logout
    <% end %>
  </div>
<% end %>

<div id="flash">
  <% if notice %>
    <div class="notice notice-info" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
      </svg>
      <p><%= sanitize notice %></p>
    </div>
  <% end %>

  <% if alert %>
    <div class="notice notice-warning" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>
      <p><%= sanitize alert %></p>
    </div>
  <% end %>

  <% if Jumpstart.config.stripe? && current_account&.payment_processor&.has_incomplete_payment? %>
    <%= link_to subscriptions_path, class: "notice notice-warning", role: :alert do %>
      <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
      <%= tag.span t(".confirm_payment"), class: "text-yellow-600 hover:text-yellow-600 hover:underline" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="w-full h-auto px-2 py-4 text-sm lg:px-6">
  <div class="flex flex-col-reverse p-4 text-sm lg:flex-row lg:justify-between lg:p-0">
    <div class="flex items-center justify-center max-w-sm self-center">
      <%= link_to root_path, class: "hidden sm:inline-block " do %>
        <%= render_svg 'butterfly_side_b', styles: "fill-current text-sky-700 hover:text-sky-500 h-6  " %>
      <% end %>
      <div class="ml-1 text-gray-700">© <%= Date.current.year %> <%= Jumpstart.config.business_name %></div>
    </div>

    <div class="flex flex-wrap justify-center">
      <%= link_to t(".about"), about_path, class: "text-gray-700 no-underline block px-4 lg:my-0 my-2" %>
      <%= link_to t(".privacy"), privacy_path, class: "text-gray-700 hover:text-gray-800 no-underline block lg:my-0 my-2 px-4" %>
      <%= link_to t(".terms"), terms_path, class: "text-gray-700 hover:text-gray-800 no-underline block lg:my-0 my-2 px-4" %>
    </div>
  </div>
</div>

app/views/shared/_left_nav.html.erb
<%# Place any links for the LEFT side of the nav bar here. Be sure to add class: "nav-link" to each item for proper spacing. %>

app/views/shared/_navbar.html+native.erb
<nav class="flex flex-wrap items-center justify-between text-sm z-10" data-controller="toggle" data-action="toggle-nav-bar@window->toggle#toggle">
  <div class="hidden fixed top-0 left-0 w-full px-4 py-2 bg-white shadow-md" data-toggle-target="toggleable">
    <div class="lg:flex-grow">
      <%= render "shared/left_nav" %>
    </div>

    <div>
      <%= render "shared/right_nav" %>

      <% if user_signed_in? %>
        <!-- Mobile menu -->
        <div class="mt-2 pt-4 pb-3 border-t border-gray-200">
          <div class="flex items-center px-2">
            <div class="flex-shrink-0">
              <%= account_avatar current_account, include_user: true, class: "rounded-full h-10 w-10" %>
            </div>
            <div class="ml-3">
              <div class="text-base font-medium text-gray-800"><%= current_account.name %></div>
            </div>
            <%= link_to notifications_path,
              class: "ml-auto bg-white flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
              data: {
                controller: "notifications",
                notifications_account_id_value: current_account.id,
                notifications_account_unread_value: @account_unread,
                notifications_total_unread_value: @total_unread,
              } do %>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" x-description="Heroicon name: outline/bell" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
              </svg>
            <% end %>
          </div>
          <div class="mt-3 space-y-1">
            <%= link_to t(".profile"), edit_user_registration_path, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100' %>
            <%= link_to t(".accounts"), accounts_path, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100' %>
            <%= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100',
              "data-controller": "turbo-native--sign-out", "data-action": "turbo-native--sign-out#signOut" %>
          </div>
        </div>

      <% else %>
        <div class="flex items-center gap-4 mt-2">
          <%= link_to t(".log_in"), new_user_session_path, class: "btn btn-light-gray btn-block" %>
          <%= link_to t(".sign_up"), new_user_registration_path, class: 'btn btn-primary btn-block' %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between px-4 py-2 bg-white border-b border-gray-200 text-sm font-medium" data-controller="toggle">
  <div class="flex items-center flex-shrink-0 mr-6">
    <%= link_to root_path do %>
      <%= render_svg "logo2", styles: "fill-current text-sky-800 hover:text-gray-800" %>
      <span class="sr-only"><%= Jumpstart.config.application_name %></span>
    <% end %>
  </div>

  <div class="block lg:hidden">
    <button type="button" id="sidebar-open" class="flex items-center p-3 text-gray-500 lg:hidden focus:outline-none focus:text-gray-700" data-action="click->toggle#toggle touch->toggle#toggle">
      <svg class="w-5 h-5 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path></svg>
    </button>
  </div>

  <div class="flex-grow hidden w-full pb-6 lg:flex lg:w-auto lg:pb-0" data-toggle-target="toggleable">
    <div class="lg:flex-grow">
      <%= render "shared/left_nav" %>
    </div>

    <div>
      <%= render "shared/right_nav" %>
      <% if user_signed_in? %>
        <div class="hidden lg:inline-block">
          <%= render "shared/notifications" %>
        </div>

        <!-- Mobile menu -->
        <div class="lg:hidden mt-2 pt-4 pb-2 border-t border-gray-200">
          <div class="flex items-center px-2">
            <div class="flex-shrink-0">
              <%= account_avatar current_account, include_user: true, class: "rounded-full h-10 w-10" %>
            </div>
            <div class="ml-3">
              <div class="text-base font-medium text-gray-800"><%= current_account.name %></div>
            </div>
            <%= link_to notifications_path, class: "ml-auto bg-white flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" do %>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" x-description="Heroicon name: outline/bell" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
              </svg>
            <% end %>
          </div>
          <div class="mt-3 space-y-1">
            <%= link_to t(".profile"), edit_user_registration_path, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100' %>
            <%= link_to t(".accounts"), accounts_path, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100' %>
            <% if current_user.admin? %>
              <%= link_to t(".admin"), admin_root_path, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100', data: { turbo: false } %>
            <% end %>
            <%= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'block p-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100' %>
          </div>
        </div>

        <!-- Main menu -->
        <div class="hidden lg:inline-flex z-10 items-center leading-none text-gray-700 no-underline align-middle rounded hover:text-gray-800 hover:bg-white">
          <div class="relative" data-controller="dropdown">
            <div data-action="click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide" role="button" class="inline-block select-none" aria-label="Profile Menu">
              <span class="flex items-center text-gray-700 appearance-none">
                <%= account_avatar current_account, include_user: true, class: "rounded-full h-8 w-8" %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="w-4 h-4"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path></svg>
              </span>
            </div>
            <div data-dropdown-target="menu" class="z-20 hidden mt-2 lg:absolute lg:right-0 dropdown-menu">
              <div class="overflow-hidden bg-white border border-gray-200 rounded shadow-md">
                <%= link_to current_account.name, current_account, class: 'border-b border-gray-200 no-underline block px-6 py-3 font-semibold text-base text-gray-800 bg-white hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
                <%= link_to t(".profile"), edit_user_registration_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
                <%= link_to t(".password"), account_password_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
                <%= link_to t(".connected_accounts"), user_connected_accounts_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' if Devise.omniauth_configs.any? %>
                <%= link_to t(".billing"), subscriptions_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' if Jumpstart.config.payments_enabled? %>
                <%= link_to t(".accounts"), accounts_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
                <%#= link_to t(".api_tokens"), api_tokens_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' if Jumpstart.config.payments_enabled? %>
                <!--
                <div class="px-6 py-3 text-xs font-bold text-gray-800 uppercase bg-white border-t border-gray-200">Accounts</div>
                -->

                <% if other_accounts.any? %>
                  <div class="px-6 py-3 text-xs font-bold text-gray-800 uppercase bg-white border-t border-gray-200">Switch Account</div>
                  <% current_user.accounts.order(name: :asc).where.not(id: current_account.id).each do |account| %>
                    <%= switch_account_button account, data: { controller: :accounts, action: "ajax:success->accounts#reconnect" }, class: 'block w-full text-left no-underline px-6 py-3 text-gray-800 bg-white hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap cursor-pointer' %>
                  <% end %>
                <% end %>

                <% if current_user.admin? %>
                  <div class="px-6 py-3 text-xs font-bold text-gray-800 uppercase bg-white border-t border-gray-200"><%= t(".admin") %></div>
                  <%= link_to t(".dashboard"), admin_root_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap', target: :_blank, data: { turbo: false } %>
                  <%= link_to 'Sidekiq', admin_sidekiq_web_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap', target: :_blank, data: { turbo: false } if defined?(::Sidekiq) %>
                <% end %>
                <% if Rails.env.development? %>
                  <div class="px-6 py-3 text-xs font-bold text-gray-800 uppercase bg-white border-t border-gray-200">Development</div>
                  <%= link_to 'Jumpstart Config', jumpstart_path(script_name: nil), class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap', data: { turbo: false } %>
                  <%= link_to 'Jumpstart Docs', jumpstart.docs_path, class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap', target: :_blank, data: { turbo: false } %>
                  <%= link_to 'Letter Opener', letter_opener_web_path(script_name: nil), class: 'no-underline block px-6 py-3 text-gray-800 bg-white  hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap', target: :_blank, data: { turbo: false } %>
                <% end %>
                <%= button_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'w-full text-left font-medium cursor-pointer px-6 py-3 border-t border-gray-200 text-gray-800 bg-white hover:bg-primary-50 transition ease-in-out duration-200 whitespace-nowrap' %>
              </div>
            </div>
          </div>
        </div>

      <% else %>
        <%= link_to t(".log_in"), new_user_session_path, class: 'nav-link' %>
        <%= link_to t(".sign_up"), new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<%= tag.div class: "z-10 mr-4 inline-flex items-center align-middle leading-none rounded no-underline text-gray-700 hover:text-gray-800 hover:bg-white",
  data: {
    controller: "notifications",
    notifications_account_id_value: current_account.id,
    notifications_account_unread_value: @account_unread,
    notifications_total_unread_value: @total_unread,
  } do %>

  <div class="relative" data-controller="dropdown">
    <%# Marks all notifications as read when menu opens by default. Remove the notifications Stimulus actions to disable this. %>
    <%= tag.button class: "inline-block select-none",
      aria: { label: "Notifications" },
      data: {
        action: "click->notifications#open touch->notifications#open click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide"
      } do %>
      <span class="appearance-none flex items-center inline-block relative text-gray-700">
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
        </svg>
        <span data-notifications-target="badge" class="hidden absolute top-0 right-0 block h-2 w-2 transform -translate-y-1/2 translate-x-1/2 rounded-full text-white shadow-solid bg-red-400"></span>
      </span>
    <% end %>

    <div data-dropdown-target="menu" class="lg:absolute lg:right-0 mt-2 hidden z-20">
      <div class="bg-white shadow rounded border border-gray-200 overflow-hidden sm:w-96">
        <%= turbo_frame_tag "notifications", loading: :lazy, target: :_top, src: notifications_path, data: { notifications_target: "list" } do %>
          <p class="p-4"><i class="fas fa-circle-notch fa-spin text-gray-400 mr-1"></i> Loading...</p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_payments_dependencies.html.erb
<% if Jumpstart.config.stripe? %>
  <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
<% end %>

<% if Jumpstart.config.braintree? || Jumpstart.config.paypal? %>
  <%= javascript_include_tag 'https://js.braintreegateway.com/web/dropin/1.20.2/js/dropin.min.js' %>
<% end %>

<%# https://developer.paypal.com/docs/checkout/how-to/braintree-integration/#1-set-up-your-client %>
<% if Jumpstart.config.paypal? %>
  <!-- Load PayPal's checkout.js Library. -->
  <script src="https://www.paypalobjects.com/api/checkout.js" data-version-4 log-level="warn"></script>

  <!-- Load the client component. -->
  <script src="https://js.braintreegateway.com/web/3.53.0/js/client.min.js"></script>

  <!-- Load the PayPal Checkout component. -->
  <script src="https://js.braintreegateway.com/web/3.53.0/js/paypal-checkout.min.js"></script>
<% end %>

<% if Jumpstart.config.paddle? %>
  <script src="https://cdn.paddle.com/paddle/paddle.js"></script>
  <script type="text/javascript">
    <% unless Rails.env.production? %>
      Paddle.Environment.set('sandbox');
    <% end %>

    Paddle.Setup({
      vendor: <%= Pay::Paddle.vendor_id %>,
      eventCallback: function(eventData) {
        updatePrices(eventData);
      }
    })

    function updatePrices(data) {
      if (data.eventData.checkout.prices) {
        let price = data.eventData.checkout.prices.customer
        document.getElementById("recurringTotal").innerHTML = `${price.total} ${price.currency}`
      }
    }
  </script>
<% end %>

app/views/shared/_right_nav.html.erb
<%# Place any links for the RIGHT side of the nav bar here. Be sure to add class: "nav-link" to each item for proper spacing. %>

<% if Jumpstart.config.payments_enabled? && (!user_signed_in? || current_account_admin?) && not_subscribed? %>
  <%= nav_link_to t(".pricing"), pricing_path, class: "nav-link" %>
<% end %>

<%= nav_link_to tag.span(t(".announcements")), announcements_path, class: ["nav-link", unread_announcements_class(current_user)] %>